Backend/leave room
Game-as-a-Service/citadels-game pull request #108
Opened 2023-08-30 17:33 UTC by snowmancc

resolves #84

2023-09-01 12:36 UTC, chiashengchen commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/citadels/spring/controllers/LeaveRoomController.java
> +        return ResponseEntity.ok().build();
API Spec 需要回離開的 userId

2023-09-01 17:47 UTC, snowmancc commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/citadels/spring/controllers/LeaveRoomController.java
> +        return ResponseEntity.ok().build();
我在想因為 request 已經帶 userId 了，這樣還需要再回傳一次嗎，因為回應 200 代表離開成功了，還是有其他部分需要帶 userId XD

2023-09-02 01:21 UTC, chiashengchen approved these changes
LGTM

2023-09-02 06:33 UTC, timt1028 commented on packages/backend/app/src/main/java/tw/waterballsa/gaas/citadels/app/usecases/LeaveRoomUseCase.java
> +        return room.orElseThrow(() -> new NotFoundException("CAN NOT FIND GAME, ID=" + roomId));
```java
return roomRepository.findRoomById(roomId).orElseThrow(() -> new NotFoundException("CAN NOT FIND GAME, ID=" + roomId));
```
沒有一定要～

2023-09-02 06:43 UTC, timt1028 commented on packages/backend/domain/src/main/java/tw/waterballsa/gaas/citadels/domain/Room.java
> +    private void transferHolderIfHolderLeave(String userId) {
assignNewHostIfCurrentHostLeaves 參考 哈哈

2023-09-02 06:50 UTC, timt1028 commented on packages/backend/domain/src/main/java/tw/waterballsa/gaas/citadels/domain/Room.java
> +            User anyUser = userIdToUser.values().stream().findAny().orElseThrow(() -> new NotFoundException("THE ROOM HAVE NOT ANY USERS"));
``` java 
User newHost or newHolder 
```

2023-09-02 06:51 UTC, timt1028 approved these changes
LGTM

2023-09-02 14:23 UTC, timt1028 requested changes
LGTM

2023-09-02 14:23 UTC, timt1028 approved these changes
LGTM

2023-09-02 14:24 UTC, merged