Backend/get rooms API #40
Game-as-a-Service/citadels-game pull request #120
Opened 2023-09-29 01:39 UTC by aprilywy

2023-09-30 08:36 UTC, timt1028 requested changes

2023-09-30 08:36 UTC, timt1028 commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/citadels/spring/repositories/data/RoomData.java
> +//    }
如果沒有用到code 可以刪掉xd

2023-09-30 08:36 UTC, timt1028 commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/citadels/spring/service/GetRoomsService.java
> +        }
你已經有寫了轉view 方式 GetRoomsView toViewModel()，但這方法轉的跟你這寫的view 架構有點不太一樣，可能要確認一下~
參考(https://github.com/Game-as-a-Service/citadels-game/issues/94)

2023-10-16 15:09 UTC, snowmancc commented on packages/backend/domain/src/main/java/tw/waterballsa/gaas/citadels/domain/Room.java
> +        OK
Room 沒有 ok 的狀態， 如果是 API 那邊要用的話，可以在 spring 那一層開一個 const 的 package, 然後建一個  RequestStatus enum 類來使用(其他 api 的也可以一起改一下XD)

2023-11-06 14:42 UTC, timt1028 commented on packages/backend/app/src/main/java/tw/waterballsa/gaas/citadels/app/usecases/GetRoomUseCase.java
> +    }
跟execute方法裡的 getRooms 重覆了 可以選一個^^

2023-11-06 14:42 UTC, timt1028 commented on packages/backend/app/src/main/java/tw/waterballsa/gaas/citadels/app/usecases/GetRoomUseCase.java
> +public class GetRoomUseCase {
是取得多個房間的UseCase

2023-11-06 14:42 UTC, timt1028 commented on packages/backend/spring/src/main/java/tw/waterballsa/gaas/citadels/spring/controllers/GetRoomsController.java
> +    class GetRoomPresenter implements GetRoomUseCase.Presenter {
取得多個房間喔

2023-11-09 14:25 UTC, timt1028 approved these changes
**LGTM**

2023-11-20 15:00 UTC, chiashengchen commented on packages/backend/domain/src/main/java/tw/waterballsa/gaas/citadels/domain/Room.java
> +@NoArgsConstructor
@NoArgsConstructor 這個註解好像沒用到 ?

2023-11-27 15:20 UTC, merged